apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cloudinit
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tenant-cluster.labels" . | nindent 4 }}
type: Opaque
data:
  userData: {{ .Files.Get "cfg/cloudinit.yaml" | b64enc }}