{{ $count := (.Values.workerSpec.count | int) }}
{{- range until $count  }}
---
apiVersion: virtualization.deckhouse.io/v1alpha2
kind: VirtualMachine
metadata:
  name: {{ $.Release.Name }}-node-{{ . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "tenant-cluster.labels" $ | nindent 4 }}
    role: worker
spec:
  runPolicy: AlwaysOn
  enableParavirtualization: true
  osType: Generic
  bootloader: BIOS
  {{- with $.Values.workerSpec.cpu }}
  cpu:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $.Values.workerSpec.memory }}
  memory:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  disruptions:
    restartApprovalMode: Automatic
  provisioning:
    type: UserDataSecret
    userDataSecretRef:
      name: {{ $.Release.Name }}-cloudinit
  blockDevices:
    - type: VirtualMachineDisk
      virtualMachineDisk:
        name: {{ $.Release.Name }}-root-node-{{ . }}
    - type: VirtualMachineDisk
      virtualMachineDisk:
        name: {{ $.Release.Name }}-data-node-{{ . }}
{{end}}