apiVersion: v1
kind: ServiceAccount
metadata:
  name: dvp-cloud-controller-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dvp-cloud-controller-manager
rules:
  - apiGroups:
    - virtualization.deckhouse.io
    resources:
    - virtualmachines
    verbs:
    - get
    - list
    - watch
  - apiGroups:
      - ""
    resources:
      - services
      - services/finalizers
      - services/status
    verbs:
      - get
      - create
      - update
      - delete
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dvp-cloud-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dvp-cloud-controller-manager
subjects:
  - kind: ServiceAccount
    name: dvp-cloud-controller-manager
---
apiVersion: v1
kind: Secret
metadata:
  name: dvp-cloud-controller-manager-secret
  annotations:
    kubernetes.io/service-account.name: dvp-cloud-controller-manager
type: kubernetes.io/service-account-token